const dotenv = require("dotenv");
dotenv.config();
module.exports = {
  CURRENT_URL: process.env.CURRENT_URL,
  GOOGLE_SIGNIN_CLIENT_ID: process.env.GOOGLE_SIGNIN_CLIENT_ID,
  GOOGLE_SIGNIN_SECRET_ID: process.env.GOOGLE_SIGNIN_SECRET_ID,
  NODEMAILER_EMAIL_ID: process.env.NODEMAILER_EMAIL_ID,
  NODEMAILER_PASS: process.env.NODEMAILER_PASS,
  SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
  MAIN_EXCEL_URL: process.env.MAIN_EXCEL_URL,
  BANK_EXCEL_URL: process.env.BANK_EXCEL_URL,
  MAIN_EXCEL_ID: process.env.MAIN_EXCEL_ID,
  BANK_EXCEL_ID: process.env.BANK_EXCEL_ID,
  STUDENT_EXCEL_URL: process.env.STUDENT_EXCEL_URL,
  ADMIN_EXCEL_URL: process.env.ADMIN_EXCEL_URL,
  PROFESSOR_EXCEL_URL: process.env.PROFESSOR_EXCEL_URL,
  ADMIN_EXCEL_ID: process.env.ADMIN_EXCEL_ID,
  STUDENT_EXCEL_ID: process.env.STUDENT_EXCEL_ID,
  PROFESSOR_EXCEL_ID: process.env.PROFESSOR_EXCEL_ID,
};
